
// **************** HOMEPAGE **************************** //
export const HOMEPAGE_GET = "HOMEPAGE_GET";
export const COMMIT_STATUS_CHANGE = "COMMIT_STATUS_CHANGE";

export const FETCH_HOMEPAGE_BEGIN = "FETCH_HOMEPAGE_BEGIN";
export const FETCH_HOMEPAGE_SUCCESS = "FETCH_HOMEPAGE_SUCCESS";
export const FETCH_HOMEPAGE_ERROR = "FETCH_HOMEPAGE_ERROR";